spring:
  application:
    name: price-rules-ai-drools
  profiles:
    active: dev
  ai:
    routing:
      strategies:
        - name: billing-review
          condition: "deal.type == 'ENTERPRISE' && deal.value > 100000"
          description: "Route enterprise deals above $100,000 to billing review"
          priority: 10
          enabled: true
          minConfidence: 0.7
        - name: technical-review
          condition: "deal.complexity == 'HIGH'"
          description: "Route high-complexity deals to technical review"
          priority: 8
          enabled: true
          minConfidence: 0.6
        - name: risk-review
          condition: "customer.riskScore > 70"
          description: "Route high-risk customers to risk review"
          priority: 9
          enabled: true
          minConfidence: 0.7
      fallback-route: general-review
      confidence-threshold: 0.7
      enable-detailed-logging: false
      enable-caching: true
      cache-ttl-seconds: 300
      max-cache-size: 1000
      enable-metrics: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/price_rules_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 60000
    connect-timeout: 10000
    vector-store:
      enabled: true
      similarity-threshold: 0.85
      max-cache-size: 10000
      ttl: 3600
      embedding-model: text-embedding-ada-002
      index-name: semantic-cache-index
      prefix: semantic:cache:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-in-production-and-use-a-very-long-secret-key}
      expiration: 86400000 # 24 hours in milliseconds

server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024

drools:
  rule-expiration: 3600 # in seconds
  rule-execution-timeout: 1000 # in milliseconds
  default-rule-path: classpath:rules/
  enable-caching: true
  max-rule-size: 1048576 # 1MB
  max-cache-size: 100
  
financial-metrics:
  default-churn-rate: 0.03 # 3% monthly churn rate
  default-customer-lifespan: 36 # 3 years average customer lifespan in months
  
pricing:
  default-currency: USD
  risk-adjustment-factor: 0.1 # 10% adjustment for high-risk customers
  volume-discount-threshold: 1000 # Minimum volume for discount eligibility

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    redis:
      enabled: true
    db:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true

logging:
  level:
    root: INFO
    com.example.pricerulesaidrools: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.drools: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/application.log
    max-size: 10MB
    max-history: 7

ai:
  openai:
    api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
    embedding-model: text-embedding-ada-002
    embedding-dimensions: 1536
  sequential-thinking:
    apiUrl: ${SEQUENTIAL_THINKING_URL:http://localhost:8081/api/sequential-thinking}
    apiKey: ${SEQUENTIAL_THINKING_API_KEY:your-api-key-here}
    connectionTimeout: 10000 # milliseconds
    readTimeout: 30000 # milliseconds
    maxThoughts: 8
    model: ${SEQUENTIAL_THINKING_MODEL:claude-3-opus-20240229}
  context7:
    apiUrl: ${CONTEXT7_URL:http://localhost:8082/api/context7}
    apiKey: ${CONTEXT7_API_KEY:your-api-key-here}
    connectionTimeout: 5000 # milliseconds
    readTimeout: 15000 # milliseconds
    defaultTokenLimit: 5000
    defaultLibraryName: drools
  puppeteer:
    url: ${PUPPETEER_URL:http://localhost:8083/api/puppeteer}
    timeout: 30000 # milliseconds

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/price_rules_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
logging:
  level:
    com.example.pricerulesaidrools: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.drools: DEBUG

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false
  redis:
    embedded: true
drools:
  enable-caching: false
server:
  port: 0

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  security:
    jwt:
      secret: ${JWT_SECRET}
logging:
  level:
    root: WARN
    com.example.pricerulesaidrools: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.drools: WARN